
# Auto generated by pluginv ensure_setup_py task
from setuptools import find_packages, setup
setup(
    name="SPS_Azure_AD".lower(),
    version="1.0.0",
    packages=find_packages(exclude=[
        "*.tests",
        "*.tests.*",
        "tests.*",
        "tests"
    ]),
    py_modules=["main"]
)
